# django_api-23c427f3abe6b532e4b1bc0f036ddd98c5d31d9f

He tenido que crear un nuevo repositorio porque tuve un problema con los migraciones
